### PR TITLE
Reduce irrealistic voltage created by remote voltage control 

### LINKED ISSUE #1124: Reduce irrealistic voltage created by remote voltage control
### Describe the current behavior

Remote voltage control is implemented by a QPV algorithm.
The controlled bus is QPV. THe controller is P only.
The equations expects that the controller delivers enough active power to the controlled bus to maintain the target voltage.
AN outerloop moves the controller to Q status if the  injections is out of its reactive limits.

But mechanically, this modifies that voltage of the controller bus - sometimes below the realistiv controls
Sometimes also, because the controllers voltage is a quadratic function of Q at the other end of al line, Q min is never reached at the conroller bus even with very low Q delivered at controlled bus.

### Describe the expected behavior

When voltage targets are not too irrealistic do not produce irrealistic voltage at the stator.

Note: the method can not protect againts completelly irrealistic voltage targets that can create divergence (imposible to find a configuration hat keep the volrage at controller bus) or produce negative voltage at controller bus and LU factorisation issues. 
For irrealisti voltage targets, that method should be used in combination with an incorrect voltage target detector such as https://github.com/powsybl/powsybl-open-loadflow/pull/1115

### Describe the steps

Proposed solution:
- If ReactiveControlLimit outerloop is used:
-   deactivate irrealistic voltage control until ReactoveLimitOuterLoop is stable (idea similar to https://github.com/powsybl/powsybl-open-loadflow/pull/1087)
-   in ReactiveLimitOuterloop set the remote controller bus with irrealistiv voltage to PQ and Qmin/Qmax. Reset their voltage to 1.

### Environment

_No response_

### Relevant Log Output

_No response_

### Extra Information

_No response_

### PR DESCRIPTION
**Pull request by vidaldid-rte**
**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [X] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
Fixes #1124

**What kind of change does this PR introduce?**
A new parameter, **voltageRemoteControlRobustMode** is introduced. With value true by default.
When the robust mode is set to true, 
 - The enforcement of realistic voltage limit is performed only after the reactive limit outerloop is stabilized

the reactive limit outerloop is modified as follow:

If the bus of a generator with remote voltage control on , and reactivie limits, is approaches the realistic voltage limit:
    - If the bus is outside its reactive limits, it is move PQ (as usual) and its voltage is set to 1pu for the next NR run
    - If the bus is inside its reactive limites, it is removed from voltage control (and Q is set to initial targetQ). Its voltage is set to 1pu for the next NR run.

**What is the current behavior?**
The Newton Raphson fails if a bus reaches a low voltage - a situation that can happen with remoted voltage control due to the PQV model.

**What is the new behavior (if this is a feature change)?**
With **voltageRemoteControlRobustMode** set to true (the default value) the resolution of networks with stressed or inconsistent remote voltage targets is more robust.

**Does this PR introduce a breaking change or deprecate an API?**
- [] Yes
- [ X ] No

### CODE REVIEW

File: src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java [hunk 1]
```diff
@@ -207,45 +215,91 @@ private static boolean switchPqPv(List<PqToPvBus> pqToPvBuses, ContextData conte
      *  - if Q equals to Qmin
```
Comment (SylvestreSakti) [inline src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java:215]: This comment should be updated :
```suggestion
     * (1) A bus PV bus can be switched to PQ in 3 cases:
     *  - if Q equals to Qmax
     *  - if Q equals to Qmin
     *  - if the controller bus is a remote controller bus and V is outside realistic voltage limits
```

File: src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java [hunk 2]
```diff
@@ -265,12 +319,19 @@ private static boolean switchReactiveControllerBusPq(List<ControllerBusToPqBus>
...
+                    case MAX_Q:
+                        LOGGER.trace("Remote reactive power controller bus '{}' -> PQ, q={} > maxQ={}", controllerBus.getId(), bus.q * PerUnit.SB,
+                                bus.qLimit * PerUnit.SB);
+                        break;
+                    case MIN_Q:
+                        LOGGER.trace("Remote reactive power controller bus '{}' -> PQ, q={} < minQ={}", controllerBus.getId(), bus.q * PerUnit.SB,
+                                bus.qLimit * PerUnit.SB);
+                        break;
+                    case MIN_V, MAX_V:
+                        LOGGER.trace("Remote reactive power controller bus '{}' -> PQ = targetQ - v outside realistic voltage limits",
```
Comment (SylvestreSakti) [inline src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java:332]: Same remark as above

**Review by SylvestreSakti — COMMENTED** [review]
Some minor remarks on the code and I did some typo fix.

File: src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java [hunk 3]
```diff
@@ -106,6 +108,16 @@ private void runOuterLoop(AcOuterLoop outerLoop, AcOuterLoopContext outerLoopCon
                 && runningContext.lastSolverResult.getStatus() == AcSolverStatus.CONVERGED
                 && runningContext.outerLoopTotalIterations < context.getParameters().getMaxOuterLoopIterations());
 
+        if (!canCheckUnrealistic && runningContext.lastUnrealisticStateFixingLoop == outerLoop && runningContext.lastSolverResult.getStatus() == AcSolverStatus.CONVERGED) {
```
[the remark this answers is not in the document]
Comment (vidaldid-rte) [reply src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java:111]: It is equivalent if you take into account that canCheckUnrealistic is defined today by "runningContext.lastUnrealisticStateFixingLoop == null"

But I prefer to explicit the condition to avoid side effect if that definition is changed.

The meaning is:
  if canCheckUnrealistic is false, then the check was not performed in solver.run
  And if we are the last outerloop that tolerates unrealistic voltage, then we must check if the loop has converged.
  
  I prefer to keep it written this way instead of assuming relationships between these variables.

File: src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java [hunk 4]
```diff
@@ -106,6 +108,16 @@ private void runOuterLoop(AcOuterLoop outerLoop, AcOuterLoopContext outerLoopCon
...
+            // This is time to check the unrealistic state
+
+            if (solver.isStateUnrealisticForSolver(context.getNetwork().getReportNode())) {
```
[the remark this answers is not in the document]
Comment (vidaldid-rte) [reply src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java:114]: I wanted to explicit the conditions.
My logic is:
First condition; we have to check now the irrealistic values.
Second condition:
   We test the values (it is not only a test since it generates a report by the way and has really to be done if previou sconditions are true)
      and f they are irrealistic we update the result.

File: src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java [hunk 5]
```diff
@@ -137,18 +139,24 @@ private boolean switchPvPq(List<ControllerBusToPqBus> pvToPqBuses, int remaining
...
+                        case MAX_Q :
+                            LOGGER.trace("Switch bus '{}' PV -> PQ, q={} > maxQ={}", controllerBus.getId(), pvToPqBus.q * PerUnit.SB,
+                                    pvToPqBus.qLimit * PerUnit.SB);
+                            break;
+                        case MIN_Q:
+                            LOGGER.trace("Switch bus '{}' PV -> PQ, q={} < minQ={}", controllerBus.getId(), pvToPqBus.q * PerUnit.SB,
+                                    pvToPqBus.qLimit * PerUnit.SB);
+                            break;
+                        case MIN_V, MAX_V:
+                            LOGGER.trace("Switch bus '{}' PV -> PQ, q={} = targetQ - v outside realistic voltage limits", controllerBus.getId(), pvToPqBus.qLimit * PerUnit.SB);
```
[the remark this answers is not in the document]
Comment (vidaldid-rte) [reply src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java:158]: Why not adding the voltage. But my intention was mostly to tell that the bus is switch to PQ with Q = target Q which is unusual. Displaying targetQ is important to me because it explain the results (and I think it disappears from your suggested message and is replaced by the  of the bus when in irrealistic conditions)

File: src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java (hunk 4 above)
[the remark this answers is not in the document]
Comment (vidaldid-rte) [reply src/main/java/com/powsybl/openloadflow/ac/AcloadFlowEngine.java]: I rewrote the part to avoid making Sonar believe this is just boolean arithmetic...

File: src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java (hunk 5 above)
[the remark this answers is not in the document]
Comment (vidaldid-rte) [reply src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java]: Trace Message updated with bus V and limits.

File: src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java (hunk 2 above)
Comment (vidaldid-rte) [reply src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java]: Info added but targetQ kept.

File: src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java [hunk 6]
```diff
@@ -349,4 +417,9 @@ public OuterLoopResult check(AcOuterLoopContext context, ReportNode reportNode)
         }
         return new OuterLoopResult(this, status);
     }
+
+    @Override
+    public boolean canFixUnrealisticState() {
+        return true;
```
Comment (SylvestreSakti) [inline src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java:423]: Shouldn't we check unrealistic state if robust mode is deactivated ?

If voltageRemoteControlRobustMode is set to `false`, I would put the value canFixUnrealisticState at `false` for this outerloop.

Comment (SylvestreSakti) [reply src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java:423]: After discussion, this value can stay to `true` because when the parameter `voltageRemoteControlRobustMode` is deactivated, `canFixUnrealisticState()` is not called.

Comment (vidaldid-rte) [reply src/main/java/com/powsybl/openloadflow/ac/outerloop/ReactiveLimitsOuterLoop.java:423]: @SylvestreSakti after more thought I still think the outerloop should return true whether or not robustMode is true.
Here is why:
   Even passively, the outerloop can fix some irrealistic voltage (as noticed by Sebastien in PR #1087 
   This is also the case of the TrasformerVoltageControlOuterloop that can passively fix irrealistic voltages (that it may introduce when unstable when continuous tapratio are not within their bounds)

    So if in the future, someone wanted to delay voltage control after this outerloop, even if the ReactiveLimitOuterloop does nothing about robustification ( reset unrealistiv V to 1, or to set PQ controller buses within diagram but outside realistic voltage), he could implement this using this method.

**Review by SylvestreSakti — APPROVED** [review]

File: src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java [hunk 7]
```diff
@@ -17,5 +17,10 @@ public interface AcSolver {
 
     String getName();
 
-    AcSolverResult run(VoltageInitializer voltageInitializer, ReportNode reportNode);
+    AcSolverResult run(VoltageInitializer voltageInitializer, ReportNode reportNode, boolean canCheckUnrealistic);
```
Comment (jeandemanged) [inline src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java:20]: no strong opinion here... asking @geofjamg also for advice...
My understanding is that now the AcSolver needs to know things happening in AcLoadFlowEngine and OuterLoops.
Would it make sense instead to:
- move `canCheckUnrealistic` to `AcLoadFlowContext`
- change the API to provide the `AcSolver` with the `AcLoadFlowContext` 
?

File: src/main/java/com/powsybl/openloadflow/network/LfBus.java [hunk 8]
```diff
@@ -21,7 +21,19 @@ public interface LfBus extends LfElement {
 
     enum QLimitType {
         MIN_Q,
-        MAX_Q
+        MAX_Q,
+        // Remote voltage control bus that have not reached a Q Limit but a realistic V limit
+        MIN_V,
+        MAX_V;
```
Comment (jeandemanged) [inline src/main/java/com/powsybl/openloadflow/network/LfBus.java:27]: minor: rename to `MIN/MAX_REALISTIC_V` ? (just for extra clarity)

File: src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java
Comment (jeandemanged) [inline src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java:1]: do you need these changes ?

File: src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java [hunk 9]
```diff
@@ -0,0 +1,274 @@
...
+        // Activate trace logs
+        LoggerContext loggerContext = (LoggerContext) LoggerFactory.getILoggerFactory();
+        loggerContext.getLogger(ReactiveLimitsOuterLoop.class).setLevel(Level.TRACE);
+    }
+
+    @AfterEach
+    void restoreLogger() {
+        LoggerContext loggerContext = (LoggerContext) LoggerFactory.getILoggerFactory();
+        loggerContext.getLogger(ReactiveLimitsOuterLoop.class).setLevel(null);
+    }
```
Comment (jeandemanged) [inline src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java:170]: do you need to keep this ?

File: src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java [hunk 10]
```diff
@@ -0,0 +1,274 @@
...
+        parametersExt.setMinRealisticVoltage(0.8);
+        parametersExt.setMaxRealisticVoltage(1.2);
+        parametersExt.setVoltageRemoteControlRobustMode(robustMode);
+        parameters.setUseReactiveLimits(true);
+        g1.newMinMaxReactiveLimits().setMinQ(-3000).setMaxQ(6000).add();
+        g1.setTargetQ(10);
+        LoadFlowResult result = loadFlowRunner.run(network, parameters);
+        if (robustMode) {
+            assertTrue(result.isFullyConverged());
+            assertReactivePowerEquals(-10, g1.getTerminal());  // The group is set to initial targetQ
```
Comment (jeandemanged) [inline src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java:227]: group  -> generator (also 2 times below)

File: src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java [hunk 11]
```diff
@@ -0,0 +1,274 @@
...
+    private Network network;
+    private Bus b1;
+    private Generator g1;
+    private LoadFlow.Runner loadFlowRunner;
+    private LoadFlowParameters parameters;
+    private OpenLoadFlowParameters parametersExt;
+
+    /**
+     * (401kV)                            (402kv)
+     *  b2 ----------------l23-------------b3---l3 (100mW)
```
Comment (jeandemanged) [inline src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java:51]: kv -> kV
mW -> MW

**Review by jeandemanged — CHANGES_REQUESTED** [review]
ok for me, except one API design topic (AcSolver) that needs to be though about maybe.
Otherwise just minor comments.

File: src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java (hunk 7 above)
Comment (geofjamg) [reply src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java:20]: Indeed unrealistic state management could be seen as a hack compared to a clean modeller/solver design where in theory the solver should not known anything regarding the physics behing the equations to solve.
Looking at the code (to confirm) we should be able to move unrealistic state management out of the solver (check is done at the very end of the solve) and have all these code in the AcLoadFlowEngine which would be a cleaner design. Also the second solver Newton krylov would also befinit from it which is not the case here.

File: src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java [hunk 12]
```diff
@@ -463,6 +468,8 @@ public enum ReportedFeatures {
 
     private boolean voltageRemoteControl = VOLTAGE_REMOTE_CONTROL_DEFAULT_VALUE;
 
+    private boolean voltageRemoteControlRobustMode = VOLTAGE_REMOTE_CONTROL_ROBUST_MODE_DEFAULT_VALUE;
```
Comment (geofjamg) [inline src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java:471]: Instead of adding this new parameter, we could just replace voltageRemoteControl by a 3 values enum. That would simplify the configuration.

**Review by geofjamg — CHANGES_REQUESTED** [review]

File: src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java (hunk 12 above)
Comment (vidaldid-rte) [reply src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java:471]: I see issues with that:
    - it is a breaking change
    - it is harder for users to use an enum value than using boolean values
    - how to make it the default ?

Now to brainstorm on the enum idea, we could consider
voltageRemoteControl:
     Off
     Robust
     Fragile ?

Comment (vidaldid-rte) [reply src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java:471]: Another proposal to kepp compatibility and have robust by default

false
true    (with robust)
reactiveLimitsOnly  (the original algo)

Comment (geofjamg) [reply src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java:471]: To keep backward compatibility you just have to keep voltageRemoteControl and setter and getter that set the corresponding mode and manage it when loading from platform config / json.
Values could be 
ON,
ON_ROBUST,
OFF

But maybe it would not worth the dev effort.

File: src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java (hunk 7 above)
Comment (jeandemanged) [reply src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java:20]: > Looking at the code (to confirm) we should be able to move unrealistic state management out of the solver (check is done at the very end of the solve) and have all these code in the AcLoadFlowEngine which would be a cleaner design. Also the second solver Newton krylov would also befinit from it which is not the case here.

Thanks for feedback, indeed if possible this would be the ideal solution. As I see it unrealistic state management is in NR solver only for historical reasons and should probably be moved out.

Comment (geofjamg) [reply src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java:20]: Yes, it is an already existing design issue even if not as visible as with this PR because only part of the solver API because of the return status.

File: src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java (hunk 12 above)
Comment (geofjamg) [reply src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java:471]: After more thought let's keep it as it is as for backward compatibility especially for pypowsybl we would need to keep old parameter and make a hack for that.

File: src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java (hunk 9 above)
Comment (vidaldid-rte) [reply src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java:170]: In reality the PV/PQ switches should probably be in the reports. 
It is useful information today. And with robust mode it would provide an explanation for PQ groups not a reactive limit bounds.

@geofjamg @jeandemanged  keep the info in logs today should I use this PR to move the PQ changes to the reports ?

File: src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java (hunk 12 above)
Comment (jeandemanged) [reply src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java:471]: I'd go for OFF/ON/ROBUST
Robust can be the default.
For backward compat we may map `false` to OFF and `true` to ROBUST (in OpenLoadFlowParameters#update).
Note: be careful of pypowsybl users which may provide `True`/`False` and not `true`/`false`.

File: src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java (hunk 9 above)
Comment (vidaldid-rte) [reply src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java]: logger activation removed.

File: src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java (hunk 10 above)
Comment (vidaldid-rte) [reply src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java]: Done

File: src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java (hunk 11 above)
Comment (vidaldid-rte) [reply src/test/java/com/powsybl/openloadflow/ac/GeneratorRemoteControlPQSwitchTest.java]: Done

File: src/main/java/com/powsybl/openloadflow/network/LfBus.java (hunk 8 above)
Comment (vidaldid-rte) [reply src/main/java/com/powsybl/openloadflow/network/LfBus.java]: Done

File: src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java
Comment (jeandemanged) [reply src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java:1]: oh sonar was the reason behind ... worst case this can be bypassed for merging, sonar most of the time points real issues, but occasionally may be too much a pain for just nothing.

Comment (vidaldid-rte) [reply src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java:1]: @geofjamg @jeandemanged 
Reporting the PV P switches is a bit large. I speparated into a different PR to merge after that one (https://github.com/powsybl/powsybl-open-loadflow/pull/1182)
This means that we may have to shut down Sonar alert on test coverage for that PR, or restore the LOGGER trace activation hack.

File: src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java (hunk 7 above)
Comment (vidaldid-rte) [reply src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java:20]: FYI, I'll create a separate PR to extract the voltage verification from Newton Raphson.

Comment (vidaldid-rte) [reply src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java:20]: @geofjamg  @jeandemanged  the PR to move the irrealistic voltage verification is here https://github.com/powsybl/powsybl-open-loadflow/pull/1188 . To be merged in main before that one on irrealistic voltage (and then I will adapt that one).

File: src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java (hunk 12 above)
Comment (vidaldid-rte) [reply src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java:471]: @jeandemanged  I would vote like Geoffroy and keep as it is. I do not see an easy way to change voltageRemoteControl to an enum without creating a breaking change in one of the following:
         JSON,  the Java parameter API or in pypowsybl.

It believe that the way to change a parameter from bool to enum would be to deprecate the old one and create a new one that would be enum based. But it seems overkill here.

Comment (jeandemanged) [reply src/main/java/com/powsybl/openloadflow/OpenLoadFlowParameters.java:471]: I am ok with this no problem, my last message was sent almost same time as Geoffroy's one, I was just slower by 1 minute :)
Agree to keep as it is.

File: src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java (hunk 7 above)
Comment (vidaldid-rte) [reply src/main/java/com/powsybl/openloadflow/ac/solver/AcSolver.java]: Merged. Requesting new review.

File: src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java
Comment (vidaldid-rte) [reply src/test/java/com/powsybl/openloadflow/ac/AcLoadFlowTransformerReactivePowerControlTest.java:1]: After more thought I reintroduced the trace log for the two tests.
I think it is good that the code that generates trace logs in the ReactiveLimitsOuterLoop is run at least once per build. This ensures that this won't break if someone needs to activate this log level for the class. So for me it justifies that we merge that.
And for this PR that was freshly refactored (moving up the realistic check) it is good to have a solide test coverage measure and easily spot was is left untested.

**Review by jeandemanged — CHANGES_REQUESTED** [review]
Thank you, just minor polishing to do.

Please also update the PR description:
- not a breaking change anymore
- mention the new parameter and its default value

**Review by jeandemanged — APPROVED** [review]
