### PR TITLE
Refacto lhs

### LINKED ISSUE #1137: DC Loadflow: Wrong bus P balance if PST connected.  (equation eval ignores constant terms)
## Short explanation :

When using getP() on LfBus object. The result is the buse's BUS_TARGET_P equation.
But when evaluating with eval(), the right-hand-side part of the terms is not taken into account.
Which results in a wrong result.
This can happen in DC LF for phase shifting or hvdc branches.

## Detailed explanation
In case of a BUS_TARGET_P equation in DC LF.
Equation terms are used for branches' getP1()/getP2() and the whole equation is used for buse's getP().

But : 
branch.getP2().eval() = ClosedBranchSide2...term::eval =  variable part + rhs part 
bus.getP().eval() = Equation::eval = sum for term in terms { term.eval() - term.rhs()}

so bus.getP().eval() != sum of branch.getP2().eval() 

in case of DC LF, for a branch P2 :
variable part = (phi_2 - phi_1) / X_12
rhs part = (A_2 - a_1) / X_12

Which means that if a branch has a pst in DC -> it has a non null rhs (Aij/Xij) and the bus.getP().eval calculation is false beacuse a part of the active power is not taken into account.

## Case where it creates a bug :

lfBus.getP().eval() is used to calculate the flow on non impedant branches after the LF (the flow on the NI branch will be the P balance of the bus minus the flows on impedant branches).

So if a bus is connected to a branch with phase shifting AND a non impedant branch. The flow will be incorrectly calculated on the non impedant branch. Resulting in a P imbalance in the bus.

### Describe the expected behavior

Calculate the actual flow balance of a bus when using lfBus.getP().eval()

### Describe the steps

_No response_

### Environment

_No response_

### Relevant Log Output

_No response_

### Extra Information

_No response_

### PR DESCRIPTION
**Pull request by vidaldid-rte**
**Please check if the PR fulfills these requirements**

- [X] The commit message follows our guidelines
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**Does this PR already have an issue describing the problem?**
 This is another approach to fix #1137

**What kind of change does this PR introduce?**
Clairify the equation model:

     evallhs = target - rhs
and
    eval = evallhs - rhs

evallhs is used to solve equations
eval is used to get the equation or term quantity

**What is the current behavior?**
Errors seen with non impedant branches in DC near a PST or an HVDC in AC emulation with P0 non null.

Potental inconsitenscies each time a non null RHS is used

**What is the new behavior (if this is a feature change)?**
Error fixed

**Does this PR introduce a breaking change or deprecate an API?**
- [ ] Yes
- [ X No

### CODE REVIEW

File: src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java [hunk 1]
```diff
@@ -178,11 +178,11 @@ static <V extends Enum<V> & Quantity, E extends Enum<E> & Quantity> EquationTerm
...
 
     /**
-     * Evaluate the equation term with an alternative state vector.
+     * Evaluate equation lhs of the equation term
      * @return value of the equation term
      */
-    default double eval(StateVector sv) {
-        throw new UnsupportedOperationException("Not implemented");
+    default double evalLhs() {
+        return eval() + (hasRhs() ? rhs() : 0);
```
Comment (SylvestreSakti) [inline src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java:185]: Should it be - rhs instead of + rhs ?
```suggestion
        return eval() - (hasRhs() ? rhs() : 0);
```

Comment (vidaldid-rte) [reply src/main/java/com/powsybl/openloadflow/equations/EquationTerm.java]: You are right. Done.
